# remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: aksakalli/jekyll-doc-theme@gh-pages  

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  pages:
    output: true
    permalink: /:path/

navigation:
  - name: Home
    link: /
  - name: Leaderboard
    link: /leaderboard.html
